### ISSUE TITLE
Specify replacements for year and author on command line

### ISSUE THREAD

**Issue by markasoftware** [kevingimbel/license#2]
Basically a `sed`. To be future compatible with licenses w/ weird fields, it could treat all unrecognized long options as a replacement, for example: `license get MIT --year 1997 --fullname 'Albert Einstein'`

**Comment by KevinGimbel** [comment]
Hey, sorry I'm replying so late! I didn't see this issue until now!

I have been thinking about this and I'd love to implement it. I'll think about the best way to handle it and then implement it. :)

**Comment by KevinGimbel** [comment]
v1.0.5 is released now with the option to repace "year" and "name".  The syntax is: 

```sh 
license get MIT --year 1997 --name 'Albert Einstein'
```

You can get the latest binary from https://github.com/kevingimbel/license/releases/tag/v1.0.5
